# need Vault

# SpecialItems [change in this Section nothing]
SpecialItems:
  Bomb: true
  Banana: true
  Thunder: true
  Mushroom: true
  Bullet-Bill: true
  Star: true

Prefix: '[&aMine&bKart&6] &c>> &f'

# MySQL Saves Table Default is minekart_playerstats [need MySQLAPI]
DatabaseName: 'minekart_playerstats'

# Would you use MySQL? Default is false [need MySQLAPI] https://github.com/TrAxMC/MySQLAPI/releases/tag/1.0.2
MySQL: false

# Default is false
BungeeCord: false

# *==* CloudNet Disabled! [Not Working] *==*
# CloudNet: false
# CloudNetLobbyGroup: Lobby

# Default is lobby
LobbyServer: lobby

# Default ist 400
WinReward: 400

# Default ist 50
LoseReward: 50

# ItemBox Default is GOLD_BLOCK
ItemBlock: GOLD_BLOCK

# Start / Finish Block Default is YELLOW_TERRACOTTA
StartBlock: YELLOW_TERRACOTTA

# Language (de or en) Default is de
lang: de

# Max Rounds are 3