Prefix: '[&aMine&bKart&6] &c>> &f'

# MySQL Saves Table Default is minekart_playerstats [need MySQLAPI]
DatabaseName: 'minekart_playerstats'

# Default is false
BungeeCord: false

# ==CloudNet Disabled!==
# CloudNet: false
# CloudNetLobbyGroup: Lobby

# Default is lobby
LobbyServer: lobby

# Would you use MySQL? Default is false [need MySQLAPI] https://github.com/TrAxMC/MySQLAPI/releases/tag/1.0.2
MySQL: false

# Default ist 400
WinReward: 400

# Default ist 50
LoseReward: 50

# ItemBox Default is GOLD_BLOCK
ItemBlock: GOLD_BLOCK

# Start / Finish Block Default is YELLOW_TERRACOTTA
StartBlock: YELLOW_TERRACOTTA

# Language (de or en) Default is de
lang: de

# Max Rounds are 3