Prefix: '[&aMine&bKart&6] &c» &f'

# MySQL Saves Table Default is minekart_playerstats
DatabaseName: 'minekart_playerstats'

#Default is false
BungeeCord: false

# Would you use MySQL? Default is false
MySQL: false

# Default ist 100
Win: 100

# ItemBox Default is GOLD_BLOCK
ItemBlock: GOLD_BLOCK

# Start / Finish Block Default is YELLOW_TERRACOTTA
StartBlock: YELLOW_TERRACOTTA

# Language (de or en) Default is de
lang: de