name: MineKart
version: 1.5.0-BETA
main: de.framedev.minekart.main.Main
api-version: 1.13
authors: [FramePlays]
depend: [WorldEdit, WorldGuard]

commands:
  minekart:
    aliases:
      - mk
      - minek
  playerstats:
    aliases:
      - plstats
      - pstats